name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libglew-dev libglm-dev

    - name: Compile
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        # Add commands to run your tests here
        echo "Running tests..."

